name: run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  formal-checks:
    name: Run
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - name: npm ci
        run: npm ci
      - name: run
        run: node run.js
      - name: list
        if: always()
        run: pwd && find . -name '*.dmp'
      - name: upload dump
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dump
          path: |
            ./**/*.dmp
